### ISSUE TITLE
Cannot access DappHub Chat

### ISSUE THREAD

**Issue by pyk** [dapphub/dapptools#737]
Cannot login via Github or reset password on DappHub Chat

![Screenshot 2021-08-13 164755](https://user-images.githubusercontent.com/2213646/129338943-53639b81-4810-4afb-b3a1-c06eb33ec199.png)

I've already clear browser cache and it still shows the same error.

Sorry if this not proper channel to report this, Just wanted to let the maintainer know

**Comment by TransmissionsDev** [comment]
we're in the same boat heh

**Comment by TransmissionsDev** [comment]
i let them know in the chat as well :)

**Comment by pyk** [comment]
Thanks @TransmissionsDev 👍

**Comment by d-xo** [comment]
I think this is fixed now.

**Comment by pyk** [comment]
I'm pretty sure that a few days ago I can confirm that the problem is fixed ser.

![Screenshot 2021-09-18 220315](https://user-images.githubusercontent.com/2213646/133893322-a9650da7-ded9-4601-8eb3-d90e0e51a4ac.png)

But somehow it happen again for me 😅

If there is discord community for dapptools please let me know ser. tysm

**Comment by transmissions11** [comment]
^^ seeing that as well now too

**Comment by mds1** [comment]
Also seeing this with GitHub login, using Brave on macOS. The error in the console is `{"isClientSafe":true,"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}`

Twitter login seems to work though so I've switched to that for now

**Comment by alberts9** [comment]
The error is back!
`{"isClientSafe":true,"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}`
Is there a discord for dapp/dapptools?

**Comment by transmissions11** [comment]
yeah github auth is still broken— you gotta login with twitter
